### ISSUE TITLE
Python error when running make start

### ISSUE THREAD

**Issue by alvxi** [chsasank/outline-wiki-docker-compose#16]
Hi, I'm trying to deploy outline via docker following your repo and guide. I run git clone, cd, make install, insert all required vars, run make https, then I run make start. When I run make install, it triggers this error:

```
root@debian:~/outline-wiki-docker-compose$ make start
=> Open https://api.slack.com/apps and Create New App
=> After creating, scroll down to 'Add features and functionality' -> 'Permissions'
=> 'https://localhost/auth/slack.callback'
Copy the above to Redirect URLs. Press Enter to continue...
=> Save, go back and scroll down to 'App Credentials'
Enter App ID [(hidden)] :
Enter Client ID [(hidden)] :
Enter Client Secret [(hidden)]:
Enter Verification Token (*not* Signing Secret) [(hidden)]:
=>run 'make start' and your server should be ready shortly.
docker-compose up -d
Creating network "outline-wiki-docker-compose_default" with the default driver
Pulling outline (outlinewiki/outline:latest)...
latest: Pulling from outlinewiki/outline
e95f33c60a64: Already exists
0f691a8bb887: Already exists
daf9b71c0a0d: Already exists
d92a928c7b7d: Already exists
23cbee05658a: Already exists
5d0f7b2ff41d: Already exists
80aae438b810: Already exists
57459f6b266a: Extracting [========================>                          ]  192.2MB/392.5MB
54efad743faf: Download complete
6af689169215: Download complete
Traceback (most recent call last):
  File "/usr/lib/python3.7/http/client.py", line 554, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.7/http/client.py", line 521, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/http/client.py", line 586, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.7/http/client.py", line 556, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 491, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.7/http/client.py", line 602, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.21.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1052, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1048, in up
    silent=options.get('--quiet-pull'),
  File "/usr/lib/python3/dist-packages/compose/project.py", line 466, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 324, in ensure_image_exists
    self.pull(silent=silent)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1149, in pull
    stream_output(output, sys.stdout))
  File "/usr/lib/python3/dist-packages/compose/progress_stream.py", line 26, in stream_output
    for event in utils.json_stream(output):
  File "/usr/lib/python3/dist-packages/compose/utils.py", line 61, in split_buffer
    for data in stream_as_text(stream):
  File "/usr/lib/python3/dist-packages/compose/utils.py", line 37, in stream_as_text
    for data in stream:
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 311, in _stream_helper
    data = reader.read(1)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
make: *** [Makefile:26: start] Error 1
```
I already tried to update all system packages, deleted all docker containers, images and network (using prune) and outline local git clone folder, and reinstall outline (with and without make https) and still trigers this error.

**Comment by chsasank** [comment]
This is something to do with docker/docker-compose. Hope it's fixed.
