### ISSUE TITLE
Something's broke after re-install (when logging in)

### ISSUE THREAD

**Issue by EJShim** [chsasank/outline-wiki-docker-compose#18]
I re-installed my wiki using `make clean` `make start` using same slack api credential keys.

docker containers are all running fine, but when I try to log in, I get : 

![image](https://user-images.githubusercontent.com/8189976/115370615-318fab00-a204-11eb-90e1-cc7eac9ed04b.png)

chrome console says : 
```
slack.callback:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

outline container console says : 
```
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```

can you help me? is it possible to use my original data??

**Comment by ramykfoury** [comment]
Same thing happens with me. Are you using `make https`?

**Comment by ramykfoury** [comment]
logged error taken from the outline docker image
```Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at model.get (/opt/outline/node_modules/sequelize-encrypted/index.js:41:79)
    at model.get (/opt/outline/node_modules/sequelize/lib/model.js:3465:41)
    at model.funcs.<computed> (/opt/outline/node_modules/sequelize/lib/model.js:1106:25)
    at model.User.getJwtToken (/opt/outline/build/server/models/User.js:186:11)
    at signIn (/opt/outline/build/server/utils/authentication.js:71:41)
    at /opt/outline/build/server/middlewares/passport.js:52:34
    at callback (/opt/outline/node_modules/@outlinewiki/koa-passport/lib/framework/koa.js:93:25)
    at Strategy.strategy.success (/opt/outline/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at verified (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:186:20)
    at Strategy._verify (/opt/outline/build/server/auth/providers/slack.js:78:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
```

and after refreshing the outline login page with the error above, it redirects to `https://mydomain.com/?notice=state-mismatch` 

Any help @chsasank?

**Comment by ramykfoury** [comment]
So other users (new users) are able to sign it correctly. This error seems to happen only with my account. I tried to revoke the permission from my account but also didn't work.

**Comment by Zeus540** [comment]
Hey 

Has anyone found a solution to issue above as I am experiencing the same issue
