### ISSUE TITLE
Email Verification with Mailgun

### ISSUE THREAD

**Issue by stephen-netu** [chsasank/outline-wiki-docker-compose#27]
```
Listening on http://localhost:3000
outline_outline.1.ne86gzh3mdkv@manager    |
outline_outline.1.ne86gzh3mdkv@manager    | 2021-09-20T00:00:36.018Z emails Sending email "Magic signin link" to icantbelieveisignedupforthis@gmail.com
outline_outline.1.ne86gzh3mdkv@manager    | (node:71) UnhandledPromiseRejectionWarning: Error: Connection timeout
outline_outline.1.ne86gzh3mdkv@manager    |     at SMTPConnection._formatError (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
outline_outline.1.ne86gzh3mdkv@manager    |     at SMTPConnection._onError (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
outline_outline.1.ne86gzh3mdkv@manager    |     at Timeout.<anonymous> (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
outline_outline.1.ne86gzh3mdkv@manager    |     at listOnTimeout (internal/timers.js:557:17)
outline_outline.1.ne86gzh3mdkv@manager    |     at processTimers (internal/timers.js:500:7)
outline_outline.1.ne86gzh3mdkv@manager    | (Use `node --trace-warnings ...` to show where the warning was created)
outline_outline.1.ne86gzh3mdkv@manager    | (node:71) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
outline_outline.1.ne86gzh3mdkv@manager    | (node:71) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```# Copy this file to .env, remove this comment and change the keys. For development
# with docker this should mostly work out of the box other than setting the Slack
# keys (for auth) and the SECRET_KEY.
#
# Please use `openssl rand -hex 32` to create SECRET_KEY
SECRET_KEY=xxx
UTILS_SECRET=xxx


# Must point to the publicly accessible URL for the installation
URL=https://outline.xxx.com
PORT=3000

# Optional. If using a Cloudfront distribution or similar the origin server
# should be set to the same as URL.
CDN_URL=http://localhost

# enforce (auto redirect to) https in production, (optional) default is true.
# set to false if your SSL is terminated at a loadbalancer, for example
FORCE_HTTPS=false

ENABLE_UPDATES=true
DEBUG=cache,presenters,events,emails,mailer,utils,multiplayer,server,services

# Third party signin credentials (at least one is required)
SLACK_KEY=xxx
SLACK_SECRET=xxx

# To configure Google auth, you'll need to create an OAuth Client ID at
# => https://console.cloud.google.com/apis/credentials
#
# When configuring the Client ID, add an Authorized redirect URI:
# https://<your Outline URL>/auth/google.callback
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Comma separated list of domains to be allowed (optional)
# If not set, all Google apps domains are allowed by default
GOOGLE_ALLOWED_DOMAINS=

# Third party credentials (optional)
SLACK_VERIFICATION_TOKEN=
SLACK_APP_ID=
SLACK_MESSAGE_ACTIONS=true
GOOGLE_ANALYTICS_ID=
SENTRY_DSN=

# AWS credentials (optional in development)
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
AWS_REGION=xx-xxxx-x
AWS_S3_UPLOAD_BUCKET_URL=http://localhost
AWS_S3_UPLOAD_BUCKET_NAME=outline-bucket
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
# uploaded s3 objects permission level, default is private
# set to "public-read" to allow public access
AWS_S3_ACL=private

# Emails configuration (optional)
SMTP_HOST=smtp.mailgun.org
SMTP_PORT=587
SMTP_USERNAME=postmaster
SMTP_PASSWORD=xxx
SMTP_FROM_EMAIL=postmaster@xxx.com
SMTP_REPLY_EMAIL=postmaster@xxx.com
SMTP_TLS_CIPHERS=STARTTLS
SMTP_SECURE=false

# Custom logo that displays on the authentication screen, scaled to height: 60px
TEAM_LOGO=xxx

# See translate.getoutline.com for a list of available language codes and their
# percentage translated.
DEFAULT_LANGUAGE=en_US
HOST=localhost
HTTP_PORT=3000
PGSSLMODE=disable
```

I cannot get Mailgun to work with the above settings.  I am unable to send a verification email to a new user.  I receive the error (at the top).  I am unsure how to fix this or even troubleshoot it.

I have tried various SMTP_TLS_CIPHERS settings with SMTP_SECURE on, as well as turning SMTP_SECURE off (as shown in current env) and switching ports.

Thank you so much for your time and assistance!

**Comment by stephen-netu** [comment]
I had to set rDNS through my provider!  Heavens!  Thank you.  :-)
